# Generated by Django 3.2.7 on 2021-11-19 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turismo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='size',
            field=models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('B', 'Big')], default='S', max_length=2),
        ),
    ]
